service: serverless-express


custom:
  dotenv:
    basePath: ./config/


provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  region: ${env:REGION}


functions:
  app:
    handler: handler.server
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true


plugins:
  - serverless-offline
  - serverless-dotenv-plugin